#
# ChangeLog for /export/doexport.sh
# 
# Generated by Trac 0.11.1
# 09/20/15 18:11:24
 
Wed, 10 Oct 2007 12:17:07 GMT Andrew Oakley <ado@…> [15eab9f12f1666f0911bea3729257956985b8c47]
	* export/doexport.sh (modified)

	Updated export script so it actually packages up the symlink and
	deletes  ...


Wed, 10 Oct 2007 11:38:59 GMT Andrew Oakley <ado@…> [d53202e5e7727af049cf8f335042b0a9a0cbbd00]
	* export/doexport.sh (modified)

	Updated export script so it creates a new_html symlink which points
	to  ...


Wed, 10 Oct 2007 11:32:49 GMT Andrew Oakley <ado@…> [d5a42212333d0aebdccc0a39cb068711dd1a1fcb]
	* export/doexport.sh (added)
	* export/template/public_html/.htaccess (added)
	* export/template/public_html/index.php (added)
	* export/template/public_html/php.ini (added)
	* export/template/system/application/config/database.php (added)

	Added update script to svn


